- name: add taps
  community.general.homebrew_tap:
    name:
      - d12frosted/emacs-plus
      - delphinus/sfmono-square

- name: update homebrew
  community.general.homebrew:
    update_homebrew: true

- name: install homebrew apps
  community.general.homebrew:
    name:
      - ansible
      - bat
      - ffmpeg
      - fzf
      - gh
      - ripgrep
      - tig
      - tree
      - tig
      - wget
      - chezmoi
      - jq
      - git
      - sqlite
      - vim
      - tmux


- name: install cask apps
  community.general.homebrew_cask:
    install_options:
      - force
    name:
      # utitlties
      - 1password-cli
      - karabiner-elements
      - raycast
      - iterm2
      - discord
      - spotify
      - vlc
      - asana
      - zoho-mail
      - balenaetcher
      - slack
      - 1password

      # dev tools
      - stoplight-studio
      - wireshark
      #- sequel-pro
      #- tableplus
      #- postman
      #- trailer
      #- burp-suite
      #- sourcetree
      - visual-studio-code

      # browsers
      - firefox
      - google-chrome
      - microsoft-edge
