- name: show dot files in finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true

- name: default dir path
  community.general.osx_defaults:
    domain: com.apple.finder
    key: NewWindowTargetPath
    type: string
    value: "file:${HOME}/Downloads/"

- name: show full path
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true

- name: screen shots blur off
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: disable-shadow
    type: bool
    value: true

- name: hidden app icon in dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: static-only
    type: bool
    value: true

- name: auto hide dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true

- name: auto hide dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: int
    value: 30

- community.general.osx_defaults:
    domain: com.apple.dock
    key: orientation
    type: string
    value: left


- name: restart finder
  shell: killall Finder

- name: restart dock
  shell: killall Dock
